version: '3.7'
services:
  app:
    container_name: esr-app
    image: app_image
    env_file:
      - docker.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src
    ports:
      - "16000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017" # Optional: expose MongoDB on a local port

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge