version: '3.7'
services:
  app:
    container_name: ers-app
    image: ers_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src
    ports:
      - "16000:8000"

networks:
  default:
    external: true
    name: app_main