apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ers.fullname" . }}
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: '{{ $value | b64enc }}'
  {{- end }}
type: Opaque
