apiVersion: v1
kind: Service
metadata:
  name: {{ include "ers.fullname" . }}
  labels:
    {{- include "ers.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ers.selectorLabels" . | nindent 4 }}
