name: Deploy to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'tests/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create cache directory
        run: mkdir -p ${{ github.workspace }}/.buildx-cache

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker containers
        run: docker compose build

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: docker compose run app pytest

      - name: Deploy to Fly.io
        if: success()
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl deploy --dockerfile ./Dockerfile --remote-only -a tech-entity-recognition --build-arg BUILDKIT_INLINE_CACHE=1