name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Fly.io
      uses: superfly/flyctl-actions/setup-flyctl@master
      with:
        fly-access-token: ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      run: |
        flyctl deploy --dockerfile ./Dockerfile --remote-only