name: Deploy to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'  
      - 'Dockerfile'
      - 'requirements/**'  
      - 'tests/**'
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/dependencies
        key: ${{ runner.os }}-dependencies-${{ hashFiles('requirements/**') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
          
    - name: Build and Push Docker Image
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        curl -L https://fly.io/install.sh | sh
        export FLYCTL_INSTALL="/home/runner/.fly"
        export PATH="$FLYCTL_INSTALL/bin:$PATH"
        flyctl auth token $FLY_API_TOKEN
        
        # Install dependencies (if cache missed)
        if [ ! -d "/tmp/dependencies" ]; then
          apt-get update && apt-get install -y gcc libpq-dev && apt clean && rm -rf /var/cache/apt/*
          pip install -U pip
          pip install --no-cache-dir -r requirements/dev.txt -t /tmp/dependencies
        fi
        
        # Build and deploy the Docker image
        flyctl deploy --dockerfile ./Dockerfile -a tech-entity-recognition --mount=type=cache,target=/tmp/dependencies